### ISSUE TITLE
Can't use number with decimals in the amount field

### ISSUE THREAD

**Issue by travisseh** [solstar-tech/easy-spl#7]
I'm hoping theres an easy answer to this but as far as I can tell you can't use decimals for the amount of tokens with transferToken() - you can only send whole tokens.

For example doing this `const result = await easySPLWallet.transferToken(myMint, toWallet, 2.5);` will result in sending 2 rather than 2.5 tokens.

Is there a way around this?

**Comment by dholms** [comment]
Thanks for the issue @travisseh 

I fixed this here: https://github.com/solstar-tech/easy-spl/pull/8

Rounding was happening in the wrong spot.

These utility functions are still incomplete. They'll fail with large enough numbers (hence the use of BN.js). There are ways to do the arithmetic & prevent rounding errors but I haven't gotten there yet.

The library should work for any relatively small tx (ie not millions of tokens)

**Comment by dholms** [comment]
republished as easy-spl@0.5.0

**Comment by travisseh** [comment]
awesome @dholms thanks a bunch! Also love the library, makes things so much simpler!
